engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: true
      UnusedFormalParameter:
        enabled: true
      Controversial/CamelCaseClassName:
        enabled: false
    config:
      languages:
        javascript:
          - mass_threshold: 80
        php:
          - mass_threshold: 56
  fixme:
    enabled: false
  phpmd:
    enabled: true
    checks:
      CleanCode/ElseExpression:
        enabled: false
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Controversial/Superglobals:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Design/TooManyPublicMethods:
        enabled: false
      Design/NpathComplexity:
        enabled: false
    config:
      file_extensions:
        - php
        - inc
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.php"
exclude_paths:
- "includes/OAuth2/**"
- "includes/adminer/**"
- "includes/elfinder/**"
- "includes/htmlpurifier/**"
- "includes/hybrid/**"
- "includes/phpimageworkshop/**"
- "includes/phpmailer/**"
- "includes/phputf8/**"
- "includes/smarty/**"
- "includes/utils/**"
- "includes/xml/**"